parameters:
    php_orchestra_api.subscriber.serializer.class: PHPOrchestra\ApiBundle\EventSubscriber\SerializerSubscriber
    php_orchestra_api.annotation_reader.class: Doctrine\Common\Annotations\AnnotationReader

services:
    php_orchestra_api.annotation_reader:
        class: %php_orchestra_api.annotation_reader.class%
    php_orchestra_api.subscriber.serializer:
        class: %php_orchestra_api.subscriber.serializer.class%
        arguments:
            - @serializer
            - @php_orchestra_api.annotation_reader
            - @controller_resolver
        tags:
            - { name: kernel.event_subscriber}
