parameters:
    open_orchestra_front.twig.orchestra_timed_twig_engine.class: OpenOrchestra\FrontBundle\Twig\OrchestraTimedTwigEngine

services:
    open_orchestra_front.twig.orchestra_timed_twig_engine:
        class: %open_orchestra_front.twig.orchestra_timed_twig_engine.class%
        arguments:
            - @twig
            - @templating.name_parser
            - @templating.locator
            - @debug.stopwatch
            - @request_stack
            - %open_orchestra_front.devices%
