parameters:
    php_orchestra_front.subscriber.dynamic_routing.class: PHPOrchestra\FrontBundle\EventSubscriber\DynamicRoutingSubscriber
    php_orchestra_front.manager.dynamic_routing.class: PHPOrchestra\FrontBundle\Manager\DynamicRoutingManager
    php_orchestra_front.manager.sitemap.class: PHPOrchestra\FrontBundle\Manager\SitemapManager
    php_orchestra_front.manager.robots.class: PHPOrchestra\FrontBundle\Manager\RobotsManager
    php_orchestra_front.database.route_loader.class: PHPOrchestra\FrontBundle\Routing\DatabaseRouteLoader
    php_orchestra_front.redirection.route_loader.class: PHPOrchestra\FrontBundle\Routing\RedirectionLoader

services:
    php_orchestra_front.subscriber.dynamic_routing:
        class: %php_orchestra_front.subscriber.dynamic_routing.class%
        arguments: [ @php_orchestra_front.manager.dynamic_routing ]
        tags:
            - { name: kernel.event_subscriber }
    php_orchestra_front.manager.dynamic_routing:
        class: %php_orchestra_front.manager.dynamic_routing.class%
        arguments:
            - @php_orchestra_model.repository.node
            - @php_orchestra_display.manager.site
            - @php_orchestra_model.repository.site
    php_orchestra.manager.current_site:
        alias: php_orchestra_display.manager.site
    php_orchestra_front.manager.sitemap:
        class: %php_orchestra_front.manager.sitemap.class%
        arguments:
            - @php_orchestra_model.repository.node
            - @router
            - @serializer
            - @filesystem
    php_orchestra_front.manager.robots:
        class: %php_orchestra_front.manager.robots.class%
        arguments:
            - @filesystem
    php_orchestra_front.redirection.route_loader:
        class: %php_orchestra_front.redirection.route_loader.class%
        arguments:
            - @php_orchestra_model.repository.redirection
            - @php_orchestra_model.repository.node
            - @php_orchestra_model.repository.site
        tags:
            - { name: routing.loader }
    php_orchestra_front.database.route_loader:
        class: %php_orchestra_front.database.route_loader.class%
        arguments:
            - @php_orchestra_model.repository.node
            - @php_orchestra_model.repository.site
        tags:
            - { name: routing.loader }
