parameters:
    open_orchestra_front.manager.sitemap.class: OpenOrchestra\FrontBundle\Manager\SitemapManager
    open_orchestra_front.manager.robots.class: OpenOrchestra\FrontBundle\Manager\RobotsManager

services:
    open_orchestra.manager.current_site:
        alias: open_orchestra_display.manager.site
    open_orchestra_front.manager.sitemap:
        class: %open_orchestra_front.manager.sitemap.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @router
            - @serializer
            - @filesystem
    open_orchestra_front.manager.robots:
        class: %open_orchestra_front.manager.robots.class%
        arguments:
            - @filesystem
    open_orchestra_front.redirection.route_loader:
        class: %open_orchestra_front.redirection.route_loader.class%
        arguments:
            - @open_orchestra_model.repository.redirection
            - @open_orchestra_model.repository.node
            - @open_orchestra_model.repository.site
        tags:
            - { name: routing.loader }
    open_orchestra_front.database.route_loader:
        class: %open_orchestra_front.database.route_loader.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @open_orchestra_model.repository.site
        tags:
            - { name: routing.loader }
